services:
  - type: web
    name: courtney-tts
    env: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: courtney-tts-db
          property: connectionString

databases:
  - name: courtney-tts-db
    databaseName: courtney_tts
    user: courtney_user